-- ============================================================
-- SCHEMA SUPABASE - Portfolio
-- Jalankan file ini di Supabase SQL Editor
-- ============================================================


-- ============================================================
-- 1. TABLE: projects
-- ============================================================
create table if not exists public.projects (
  id            bigint generated by default as identity primary key,
  "Title"       text not null,
  "Description" text,
  "Img"         text,
  "TechStack"   text[],
  "Features"    text[],
  "Link"        text,
  "Github"      text,
  created_at    timestamptz default now() not null
);

-- RLS
alter table public.projects enable row level security;

-- Siapa saja bisa baca
create policy "Public read projects"
  on public.projects for select
  using (true);

-- Hanya user yang login (admin) bisa insert/update/delete
create policy "Auth insert projects"
  on public.projects for insert
  with check (auth.role() = 'authenticated');

create policy "Auth update projects"
  on public.projects for update
  using (auth.role() = 'authenticated');

create policy "Auth delete projects"
  on public.projects for delete
  using (auth.role() = 'authenticated');


-- ============================================================
-- 2. TABLE: certificates
-- ============================================================
create table if not exists public.certificates (
  id         bigint generated by default as identity primary key,
  "Img"      text not null,
  created_at timestamptz default now() not null
);

-- RLS
alter table public.certificates enable row level security;

create policy "Public read certificates"
  on public.certificates for select
  using (true);

create policy "Auth insert certificates"
  on public.certificates for insert
  with check (auth.role() = 'authenticated');

create policy "Auth delete certificates"
  on public.certificates for delete
  using (auth.role() = 'authenticated');


-- ============================================================
-- 3. TABLE: portfolio_comments
-- ============================================================
create table if not exists public.portfolio_comments (
  id            bigint generated by default as identity primary key,
  user_name     text not null,
  content       text not null,
  profile_image text,
  is_pinned     boolean default false not null,
  created_at    timestamptz default now() not null
);

-- RLS
alter table public.portfolio_comments enable row level security;

-- Siapa saja bisa baca dan insert (form komentar publik)
create policy "Public read comments"
  on public.portfolio_comments for select
  using (true);

create policy "Public insert comments"
  on public.portfolio_comments for insert
  with check (true);

-- Hanya admin yang bisa update (pin) dan delete
create policy "Auth update comments"
  on public.portfolio_comments for update
  using (auth.role() = 'authenticated');

create policy "Auth delete comments"
  on public.portfolio_comments for delete
  using (auth.role() = 'authenticated');

-- Enable realtime untuk portfolio_comments
alter publication supabase_realtime add table public.portfolio_comments;


-- ============================================================
-- 4. STORAGE BUCKETS
-- Buat manual di Supabase Dashboard > Storage, atau jalankan ini
-- ============================================================

-- Bucket untuk gambar project
insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict do nothing;

-- Bucket untuk gambar certificate
insert into storage.buckets (id, name, public)
values ('certificate-images', 'certificate-images', true)
on conflict do nothing;

-- Bucket untuk foto profil komentar
insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict do nothing;

-- Storage policies: siapa saja bisa baca (public bucket)
create policy "Public read project-images"
  on storage.objects for select
  using (bucket_id = 'project-images');

create policy "Auth upload project-images"
  on storage.objects for insert
  with check (bucket_id = 'project-images' and auth.role() = 'authenticated');

create policy "Auth delete project-images"
  on storage.objects for delete
  using (bucket_id = 'project-images' and auth.role() = 'authenticated');

-- Certificate images
create policy "Public read certificate-images"
  on storage.objects for select
  using (bucket_id = 'certificate-images');

create policy "Auth upload certificate-images"
  on storage.objects for insert
  with check (bucket_id = 'certificate-images' and auth.role() = 'authenticated');

create policy "Auth delete certificate-images"
  on storage.objects for delete
  using (bucket_id = 'certificate-images' and auth.role() = 'authenticated');

-- Profile images (upload boleh siapa saja karena form komentar publik)
create policy "Public read profile-images"
  on storage.objects for select
  using (bucket_id = 'profile-images');

create policy "Public upload profile-images"
  on storage.objects for insert
  with check (bucket_id = 'profile-images');
